targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      hive_generator:
        generate_for:
          - lib/data/models/**.dart
        options:
          ignore_front_matter: false